import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:roster_co/constants/close_button.dart';

Future<IconData?> showIconPicker(
    {required BuildContext context, IconData? defalutIcon}) async {
  final List<int> iconMenuItemsCode = [
    FontAwesomeIcons.a.codePoint,
    FontAwesomeIcons.addressBook.codePoint,
    FontAwesomeIcons.b.codePoint,
    FontAwesomeIcons.baby.codePoint,
    FontAwesomeIcons.babyCarriage.codePoint,
    FontAwesomeIcons.basketball.codePoint,
    FontAwesomeIcons.book.codePoint,
    FontAwesomeIcons.bowlRice.codePoint,
    FontAwesomeIcons.brain.codePoint,
    FontAwesomeIcons.bug.codePoint,
    FontAwesomeIcons.bugSlash.codePoint,
    FontAwesomeIcons.c.codePoint,
    FontAwesomeIcons.calculator.codePoint,
    FontAwesomeIcons.camera.codePoint,
    FontAwesomeIcons.champagneGlasses.codePoint,
    FontAwesomeIcons.chessBoard.codePoint,
    FontAwesomeIcons.children.codePoint,
    FontAwesomeIcons.clipboardCheck.codePoint,
    FontAwesomeIcons.cloudBolt.codePoint,
    FontAwesomeIcons.cloudMoonRain.codePoint,
    FontAwesomeIcons.cloudSunRain.codePoint,
    FontAwesomeIcons.code.codePoint,
    FontAwesomeIcons.codeBranch.codePoint,
    FontAwesomeIcons.codeCompare.codePoint,
    FontAwesomeIcons.cubes.codePoint,
    FontAwesomeIcons.d.codePoint,
    FontAwesomeIcons.divide.codePoint,
    FontAwesomeIcons.dollarSign.codePoint,
    FontAwesomeIcons.dove.codePoint,
    FontAwesomeIcons.droplet.codePoint,
    FontAwesomeIcons.e.codePoint,
    FontAwesomeIcons.f.codePoint,
    FontAwesomeIcons.faceGrinHearts.codePoint,
    FontAwesomeIcons.faceGrinWink.codePoint,
    FontAwesomeIcons.file.codePoint,
    FontAwesomeIcons.fileCode.codePoint,
    FontAwesomeIcons.flask.codePoint,
    FontAwesomeIcons.flag.codePoint,
    FontAwesomeIcons.folder.codePoint,
    FontAwesomeIcons.folderOpen.codePoint,
    FontAwesomeIcons.g.codePoint,
    FontAwesomeIcons.ghost.codePoint,
    FontAwesomeIcons.gift.codePoint,
    FontAwesomeIcons.globe.codePoint,
    FontAwesomeIcons.graduationCap.codePoint,
    FontAwesomeIcons.guitar.codePoint,
    FontAwesomeIcons.h.codePoint,
    FontAwesomeIcons.handHoldingDollar.codePoint,
    FontAwesomeIcons.hashtag.codePoint,
    FontAwesomeIcons.headphones.codePoint,
    FontAwesomeIcons.heart.codePoint,
    FontAwesomeIcons.heartCrack.codePoint,
    FontAwesomeIcons.heartPulse.codePoint,
    FontAwesomeIcons.house.codePoint,
    FontAwesomeIcons.houseChimneyMedical.codePoint,
    FontAwesomeIcons.i.codePoint,
    FontAwesomeIcons.infinity.codePoint,
    FontAwesomeIcons.j.codePoint,
    FontAwesomeIcons.k.codePoint,
    FontAwesomeIcons.l.codePoint,
    FontAwesomeIcons.laptopCode.codePoint,
    FontAwesomeIcons.m.codePoint,
    FontAwesomeIcons.mapLocationDot.codePoint,
    FontAwesomeIcons.microphone.codePoint,
    FontAwesomeIcons.music.codePoint,
    FontAwesomeIcons.n.codePoint,
    FontAwesomeIcons.noteSticky.codePoint,
    FontAwesomeIcons.o.codePoint,
    FontAwesomeIcons.p.codePoint,
    FontAwesomeIcons.palette.codePoint,
    FontAwesomeIcons.paw.codePoint,
    FontAwesomeIcons.peace.codePoint,
    FontAwesomeIcons.penToSquare.codePoint,
    FontAwesomeIcons.personHiking.codePoint,
    FontAwesomeIcons.pizzaSlice.codePoint,
    FontAwesomeIcons.planeDeparture.codePoint,
    FontAwesomeIcons.podcast.codePoint,
    FontAwesomeIcons.puzzlePiece.codePoint,
    FontAwesomeIcons.q.codePoint,
    FontAwesomeIcons.quoteLeft.codePoint,
    FontAwesomeIcons.r.codePoint,
    FontAwesomeIcons.robot.codePoint,
    FontAwesomeIcons.rocket.codePoint,
    FontAwesomeIcons.s.codePoint,
    FontAwesomeIcons.seedling.codePoint,
    FontAwesomeIcons.shapes.codePoint,
    FontAwesomeIcons.shareNodes.codePoint,
    FontAwesomeIcons.shield.codePoint,
    FontAwesomeIcons.snowflake.codePoint,
    FontAwesomeIcons.t.codePoint,
    FontAwesomeIcons.tags.codePoint,
    FontAwesomeIcons.terminal.codePoint,
    FontAwesomeIcons.trademark.codePoint,
    FontAwesomeIcons.truckFast.codePoint,
    FontAwesomeIcons.u.codePoint,
    FontAwesomeIcons.userAstronaut.codePoint,
    FontAwesomeIcons.userClock.codePoint,
    FontAwesomeIcons.userDoctor.codePoint,
    FontAwesomeIcons.userGraduate.codePoint,
    FontAwesomeIcons.userNinja.codePoint,
    FontAwesomeIcons.userInjured.codePoint,
    FontAwesomeIcons.userSecret.codePoint,
    FontAwesomeIcons.userPen.codePoint,
    FontAwesomeIcons.userShield.codePoint,
    FontAwesomeIcons.v.codePoint,
    FontAwesomeIcons.video.codePoint,
    FontAwesomeIcons.virus.codePoint,
    FontAwesomeIcons.virusCovid.codePoint,
    FontAwesomeIcons.virusCovidSlash.codePoint,
    FontAwesomeIcons.vrCardboard.codePoint,
    FontAwesomeIcons.w.codePoint,
    FontAwesomeIcons.wallet.codePoint,
    FontAwesomeIcons.wheatAwn.codePoint,
    FontAwesomeIcons.waveSquare.codePoint,
    FontAwesomeIcons.x.codePoint,
    FontAwesomeIcons.y.codePoint,
    FontAwesomeIcons.z.codePoint,
  ];
  final List<IconData> iconMenuItems = [
    FontAwesomeIcons.a,
    FontAwesomeIcons.addressBook,
    FontAwesomeIcons.b,
    FontAwesomeIcons.baby,
    FontAwesomeIcons.babyCarriage,
    FontAwesomeIcons.basketball,
    FontAwesomeIcons.book,
    FontAwesomeIcons.bowlRice,
    FontAwesomeIcons.brain,
    FontAwesomeIcons.bug,
    FontAwesomeIcons.bugSlash,
    FontAwesomeIcons.c,
    FontAwesomeIcons.calculator,
    FontAwesomeIcons.camera,
    FontAwesomeIcons.champagneGlasses,
    FontAwesomeIcons.chessBoard,
    FontAwesomeIcons.children,
    FontAwesomeIcons.clipboardCheck,
    FontAwesomeIcons.cloudBolt,
    FontAwesomeIcons.cloudMoonRain,
    FontAwesomeIcons.cloudSunRain,
    FontAwesomeIcons.code,
    FontAwesomeIcons.codeBranch,
    FontAwesomeIcons.codeCompare,
    FontAwesomeIcons.cubes,
    FontAwesomeIcons.d,
    FontAwesomeIcons.divide,
    FontAwesomeIcons.dollarSign,
    FontAwesomeIcons.dove,
    FontAwesomeIcons.droplet,
    FontAwesomeIcons.e,
    FontAwesomeIcons.f,
    FontAwesomeIcons.faceGrinHearts,
    FontAwesomeIcons.faceGrinWink,
    FontAwesomeIcons.file,
    FontAwesomeIcons.fileCode,
    FontAwesomeIcons.flask,
    FontAwesomeIcons.flag,
    FontAwesomeIcons.folder,
    FontAwesomeIcons.folderOpen,
    FontAwesomeIcons.g,
    FontAwesomeIcons.ghost,
    FontAwesomeIcons.gift,
    FontAwesomeIcons.globe,
    FontAwesomeIcons.graduationCap,
    FontAwesomeIcons.guitar,
    FontAwesomeIcons.h,
    FontAwesomeIcons.handHoldingDollar,
    FontAwesomeIcons.hashtag,
    FontAwesomeIcons.headphones,
    FontAwesomeIcons.heart,
    FontAwesomeIcons.heartCrack,
    FontAwesomeIcons.heartPulse,
    FontAwesomeIcons.house,
    FontAwesomeIcons.houseChimneyMedical,
    FontAwesomeIcons.i,
    FontAwesomeIcons.infinity,
    FontAwesomeIcons.j,
    FontAwesomeIcons.k,
    FontAwesomeIcons.l,
    FontAwesomeIcons.laptopCode,
    FontAwesomeIcons.m,
    FontAwesomeIcons.mapLocationDot,
    FontAwesomeIcons.microphone,
    FontAwesomeIcons.music,
    FontAwesomeIcons.n,
    FontAwesomeIcons.noteSticky,
    FontAwesomeIcons.o,
    FontAwesomeIcons.p,
    FontAwesomeIcons.palette,
    FontAwesomeIcons.paw,
    FontAwesomeIcons.peace,
    FontAwesomeIcons.penToSquare,
    FontAwesomeIcons.personHiking,
    FontAwesomeIcons.pizzaSlice,
    FontAwesomeIcons.planeDeparture,
    FontAwesomeIcons.podcast,
    FontAwesomeIcons.puzzlePiece,
    FontAwesomeIcons.q,
    FontAwesomeIcons.quoteLeft,
    FontAwesomeIcons.r,
    FontAwesomeIcons.robot,
    FontAwesomeIcons.rocket,
    FontAwesomeIcons.s,
    FontAwesomeIcons.seedling,
    FontAwesomeIcons.shapes,
    FontAwesomeIcons.shareNodes,
    FontAwesomeIcons.shield,
    FontAwesomeIcons.snowflake,
    FontAwesomeIcons.t,
    FontAwesomeIcons.tags,
    FontAwesomeIcons.terminal,
    FontAwesomeIcons.trademark,
    FontAwesomeIcons.truckFast,
    FontAwesomeIcons.u,
    FontAwesomeIcons.userAstronaut,
    FontAwesomeIcons.userClock,
    FontAwesomeIcons.userDoctor,
    FontAwesomeIcons.userGraduate,
    FontAwesomeIcons.userNinja,
    FontAwesomeIcons.userInjured,
    FontAwesomeIcons.userSecret,
    FontAwesomeIcons.userPen,
    FontAwesomeIcons.userShield,
    FontAwesomeIcons.v,
    FontAwesomeIcons.video,
    FontAwesomeIcons.virus,
    FontAwesomeIcons.virusCovid,
    FontAwesomeIcons.virusCovidSlash,
    FontAwesomeIcons.vrCardboard,
    FontAwesomeIcons.w,
    FontAwesomeIcons.wallet,
    FontAwesomeIcons.wheatAwn,
    FontAwesomeIcons.waveSquare,
    FontAwesomeIcons.x,
    FontAwesomeIcons.y,
    FontAwesomeIcons.z,
  ];
  IconData? selectedIcon = defalutIcon;

  await showDialog(
    context: context,
    builder: (_) => AlertDialog(
      shape: const RoundedRectangleBorder(
          borderRadius: BorderRadius.all(Radius.circular(32.0))),
      title: Row(
        mainAxisAlignment: MainAxisAlignment.end,
        children: const [
          Center(
              child: Text(
            'Pick an Icon',
          )),
          SizedBox(
            width: 20,
          ),
          CustomCloseButton(size: 35)
        ],
      ),
      content: Container(
        width: 300,
        height: 300,
        alignment: Alignment.center,
        child: Scrollbar(
          thickness: 5,
          radius: const Radius.circular(10),
          child: GridView.builder(
              physics: const BouncingScrollPhysics(),
              gridDelegate: const SliverGridDelegateWithMaxCrossAxisExtent(
                  maxCrossAxisExtent: 60,
                  childAspectRatio: 1 / 1,
                  crossAxisSpacing: 10,
                  mainAxisSpacing: 10),
              itemCount: iconMenuItems.length,
              itemBuilder: (_, index) => Container(
                    key: ValueKey(iconMenuItems[index].codePoint),
                    padding: const EdgeInsets.all(10),
                    child: Center(
                      child: IconButton(
                        color: const Color.fromARGB(255, 56, 56, 56),
                        iconSize: 30,
                        icon: Icon(
                          iconMenuItems[index],
                        ),
                        onPressed: () {
                          selectedIcon = iconMenuItems[index];
                          Navigator.of(context).pop();
                        },
                      ),
                    ),
                  )),
        ),
      ),
    ),
  );

  return selectedIcon;
}
